#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d File Open Edit About

bspc config border_width        2
bspc config window_gap          10
bspc config top_padding		37

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Nitrogen state=floating follow=on
bspc rule -a Chromium desktop='^4' follow=on
bspc rule -a mpv state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a Xarchiver focus=on state=floating
bspc rule -a Android-File-Transfer state=floating
bspc rule -a qBittorrent desktop='^4' follow=on
bspc rule -a WasIstLos desktop='^4' follow=on state=floating
bspc rule -a Screenkey manage=off
bspc rule -a isoimagewriter state=floating
bspc rule -a wine state=floating
bspc rule -a deadbeef state=floating

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
polybar -r &
nm-applet &
xfce4-power-manager &
dunst &
nitrogen --restore &
