#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d File Edit View Open Go Etc Vim Find Tab Help

bspc config border_width        1
bspc config window_gap          13
bspc config top_padding		 	    48

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Nitrogen desktop='^3' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Thunar state=floating
bspc rule -a Xarchiver focus=on state=floating
bspc rule -a Android-File-Transfer state=floating
bspc rule -a Screenkey manage=off

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
polybar -r &
nm-applet &
xfce4-power-manager &
dunst &
xsetroot -cursor_name left_ptr &
nitrogen --restore &
picom &
